run:
  deadline: 5m

linters:
  enable-all: true
  disable:
    - dupl
    - errcheck
    - exhaustivestruct
    - gochecknoglobals
    - gomnd
    - lll
    - nlreturn
    - paralleltest
    - scopelint
    - testpackage
    - wsl
