language: go
sudo: false
go:
  - 1.11.x
  - tip
env:
  - GO111MODULE=on
install:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - make testdeps
script:
  - make golint coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
