language: go
sudo: false
go:
  - 1.8.x
  - 1.9
  - tip
install:
  - export GOROOT=$(go env GOROOT)
  - make testdeps
script:
  - make lint coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
