language: go
sudo: false
cache:
  directories:
    - $GOPATH/pkg
go:
  - 1.x
env:
  global:
    - GO111MODULE=on
install:
  - export GOCACHE=$GOPATH/pkg/cache
  - curl https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINDIR=$GOPATH/bin sh
  - make testdeps
script:
  - make golint coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
