language: go
sudo: false
go:
  - 1.x
env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
install:
  - curl https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINDIR=$GOPATH/bin sh
  - make testdeps
script:
  - make golint coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
