[[constraint]]
  name = "github.com/NYTimes/gizmo"
  version = "0.4.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/tsuru/tsuru"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true
