[[constraint]]
  branch = "master"
  name = "github.com/NYTimes/gizmo"

[[constraint]]
  name = "github.com/NYTimes/gziphandler"
  version = "1.0.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/tsuru/tsuru"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true
