name: Build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
  schedule:
    - cron: "2 0 * * 1"
jobs:
  build:
    strategy:
      matrix:
        go_version:
          - 1.12.x
          - 1.13.x

    name: Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1.0.2
        id: go
        with:
          go-version: ${{ matrix.go_version }}

      - uses: actions/checkout@v1.0.0

      - name: install-deps
        run: make testdeps
        env:
          GOPROXY: https://proxy.golang.org

      - name: run-linter
        uses: docker://golangci/golangci-lint
        env:
          GOROOT: /usr/local/go
        with:
          entrypoint: make
          args: golint

      - name: run-tests
        run: make coverage
